#!/system/bin/sh
#
# Print startup info
#

# echo "2048" > /sys/devices/virtual/bdi/179:0/read_ahead_kb;
echo "sio" > /sys/block/mmcblk0/queue/scheduler
# echo "ondemand" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
